import earbudsImg from '../assets/earbuds.png';
import headphonesImg from '../assets/headphones.png';
import smartwatchImg from '../assets/smartwatch.png';
import backpackImg from '../assets/backpack.png';
import waterBottleImg from '../assets/water_bottle.png';

// 50 products under Electronics sub-categories: Audio, Wearables, Keyboards & Mice, Smart Home, Power & Cables
// Every product has a completely unique and distinct image URL.
export const MOCK_PRODUCTS = [
  // --- SUB-CATEGORY: AUDIO (1-10) ---
  {
    id: "aud-1",
    name: "SoundFlow Wireless Earbuds",
    category: "Electronics",
    subCategory: "Audio",
    price: 3999,
    originalPrice: 5999,
    rating: 4.7,
    reviews: 142,
    stock: 15,
    description: "Experience absolute freedom with active noise cancellation, deep bass signature, and sweat-resistant ergonomics.",
    specs: { "Battery Life": "32 Hours", "Connectivity": "Bluetooth 5.3", "Waterproof": "IPX7 Rated", "ANC": "Yes" },
    features: ["Hi-Fi Stereo Drivers", "Smart Touch Controls", "Quad-Microphone Calls", "Qi Wireless Charging"],
    color: "from-indigo-500 to-blue-600",
    iconName: "Earphones",
    image: earbudsImg
  },
  {
    id: "aud-2",
    name: "AuraBeats Studio Headphones",
    category: "Electronics",
    subCategory: "Audio",
    price: 9999,
    originalPrice: 14999,
    rating: 4.9,
    reviews: 88,
    stock: 8,
    description: "Over-ear luxury audio built with hybrid ANC and memory-foam leather cups for immersive audiophile listening.",
    specs: { "Battery Life": "50 Hours", "Connectivity": "Bluetooth 5.2 / Aux", "Weight": "260g", "ANC": "Hybrid ANC" },
    features: ["Hi-Res Audio Certified", "Multi-point connection", "Collapsible design", "Fast USB-C Charging"],
    color: "from-purple-500 to-indigo-600",
    iconName: "Headphones",
    image: headphonesImg
  },
  {
    id: "aud-3",
    name: "SonicBoom Portable Speaker",
    category: "Electronics",
    subCategory: "Audio",
    price: 4999,
    originalPrice: 7999,
    rating: 4.6,
    reviews: 120,
    stock: 20,
    description: "Rugged waterproof outdoor speaker delivering 360-degree sound projection and dual passive radiators for deep bass.",
    specs: { "Output Power": "24W", "Battery Life": "18 Hours", "Waterproof": "IP67 Rated", "Weight": "480g" },
    features: ["Dynamic RGB LED sync", "PartyConnect linkable", "Built-in power bank", "Bluetooth 5.1 range"],
    color: "from-cyan-500 to-blue-600",
    iconName: "Audio",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "aud-4",
    name: "AeroVoice Wireless Mic Pro",
    category: "Electronics",
    subCategory: "Audio",
    price: 7999,
    originalPrice: 11999,
    rating: 4.8,
    reviews: 54,
    stock: 6,
    description: "Dual-channel lapel microphone kit designed for content creators, vloggers, and mobile journalists.",
    specs: { "Range": "150 meters", "Latency": "15ms ultra-low", "Battery Life": "6 Hours (24h w/ case)", "Channels": "Dual" },
    features: ["Real-time monitoring", "Intelligent Noise Reduction", "Universal DSLR/Phone adapters", "Wind muff included"],
    color: "from-zinc-700 to-slate-900",
    iconName: "Microphone",
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "aud-5",
    name: "VoxBar Cinema Soundbar",
    category: "Electronics",
    subCategory: "Audio",
    price: 12999,
    originalPrice: 18999,
    rating: 4.5,
    reviews: 73,
    stock: 12,
    description: "Upgrade your TV audio setup with Dolby Atmos virtualization and an integrated wireless subwoofer.",
    specs: { "Total Power": "120W", "Channels": "2.1 Channel", "Inputs": "HDMI ARC, Optical, Bluetooth", "Width": "32 inches" },
    features: ["Dolby Digital Plus decode", "Dialogue enhancer mode", "Wall-mountable kit", "Remote control inclusion"],
    color: "from-blue-800 to-slate-900",
    iconName: "Soundbar",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "aud-6",
    name: "EchoBuds Lite Earphones",
    category: "Electronics",
    subCategory: "Audio",
    price: 1999,
    originalPrice: 2999,
    rating: 4.3,
    reviews: 210,
    stock: 45,
    description: "Pocket-sized true wireless earbuds with punchy bass, long battery life, and crystal clear call qualities.",
    specs: { "Battery Life": "20 Hours", "Connectivity": "Bluetooth 5.2", "Waterproof": "IPX4 Rated", "Drivers": "8mm Dynamic" },
    features: ["Touch control sensors", "Instant auto-pairing", "USB-C quick charge", "Voice assistant integration"],
    color: "from-emerald-500 to-teal-600",
    iconName: "Earphones",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "aud-7",
    name: "MelodyX Neckband Pro",
    category: "Electronics",
    subCategory: "Audio",
    price: 1499,
    originalPrice: 2499,
    rating: 4.4,
    reviews: 165,
    stock: 35,
    description: "Ergonomic collar-style wireless neckband featuring magnetic ear tips and dual bass boosting chambers.",
    specs: { "Battery Life": "24 Hours", "Connectivity": "Bluetooth 5.0", "Weight": "35g", "Charging Time": "1.5 Hours" },
    features: ["Magnetic instant-off play", "Vibration call alerts", "Tangle-free wires", "Siri/Google shortcut button"],
    color: "from-rose-500 to-purple-600",
    iconName: "Earphones",
    image: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "aud-8",
    name: "Pulse DJ Headphones Pro",
    category: "Electronics",
    subCategory: "Audio",
    price: 6499,
    originalPrice: 9999,
    rating: 4.7,
    reviews: 42,
    stock: 10,
    description: "Professional monitor headphones featuring 90-degree swiveling earcups and 50mm neodymium drivers.",
    specs: { "Driver Size": "50mm", "Impedance": "32 Ohms", "Frequency Range": "15Hz - 28kHz", "Detachable Cable": "Yes" },
    features: ["Coiled cable included", "Over-ear ambient isolation", "Foldable travel design", "Gold-plated connectors"],
    color: "from-amber-600 to-orange-700",
    iconName: "Headphones",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "aud-9",
    name: "PureSound DAC Amplifier",
    category: "Electronics",
    subCategory: "Audio",
    price: 8999,
    originalPrice: 12999,
    rating: 4.8,
    reviews: 31,
    stock: 5,
    description: "Hi-Res digital-to-analog converter and headphone amplifier to unlock premium studio detail from your laptop.",
    specs: { "DAC Chip": "ES9038Q2M", "Output Power": "220mW at 32Ω", "Inputs": "USB Type-C, Coaxial", "Format Support": "DSD512, 32bit/768kHz" },
    features: ["Aluminium alloy chassis", "Zero audio latency", "Bicolor status indicators", "Independent volume knob"],
    color: "from-slate-600 to-zinc-800",
    iconName: "Audio",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "aud-10",
    name: "StudioMonitor Speakers Pair",
    category: "Electronics",
    subCategory: "Audio",
    price: 18999,
    originalPrice: 24999,
    rating: 4.9,
    reviews: 28,
    stock: 4,
    description: "Active bookshelf studio monitors delivering authentic acoustic responses for mixing, mastering, and editing.",
    specs: { "Amplification": "Bi-amped Class D", "Total RMS": "80W", "Tweeter": "1 inch silk dome", "Woofer": "4 inch woven carbon fiber" },
    features: ["Room tuning switches", "Balanced TRS / RCA inputs", "Vibration isolation pads", "Wooden MDF cabinets"],
    color: "from-amber-800 to-yellow-900",
    iconName: "Audio",
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&auto=format&fit=crop&q=60"
  },

  // --- SUB-CATEGORY: WEARABLES (11-20) ---
  {
    id: "wear-1",
    name: "Chronos Active Smart Watch",
    category: "Electronics",
    subCategory: "Wearables",
    price: 15999,
    originalPrice: 19999,
    rating: 4.7,
    reviews: 112,
    stock: 18,
    description: "Premium smartwatch with aerospace titanium bezel, active GPS mapping, and always-on AMOLED dashboard.",
    specs: { "Display": "1.43\" AMOLED", "Battery Life": "8 Days", "Waterproof": "5 ATM Rated", "Sensors": "Heart, SpO2, Sleep, GPS" },
    features: ["120+ Workout Modes", "NFC tap payments", "Bluetooth voice calling", "Custom watch faces"],
    color: "from-rose-500 to-red-600",
    iconName: "Watch",
    image: smartwatchImg
  },
  {
    id: "wear-2",
    name: "AuraFit Band 5",
    category: "Electronics",
    subCategory: "Wearables",
    price: 2999,
    originalPrice: 4999,
    rating: 4.4,
    reviews: 188,
    stock: 30,
    description: "Ultra-lightweight activity tracker featuring auto fitness detection, step counts, and sleep monitoring.",
    specs: { "Display": "1.1\" OLED Color", "Battery Life": "14 Days", "Waterproof": "IP68 Certified", "Weight": "18g" },
    features: ["24/7 heart monitors", "Stress relief breathing guide", "Camera shutter trigger", "Call & text vibrations"],
    color: "from-teal-500 to-emerald-600",
    iconName: "Watch",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "wear-3",
    name: "Titanium Smart Ring",
    category: "Electronics",
    subCategory: "Wearables",
    price: 11999,
    originalPrice: 16999,
    rating: 4.6,
    reviews: 45,
    stock: 10,
    description: "Discreet wellness wearable tracking skin temperature, activity index, and cardiac trends without screen clutter.",
    specs: { "Material": "Fighter-grade Titanium", "Battery Life": "6 Days", "Waterproof": "Up to 50 meters", "Sizes": "7, 8, 9, 10, 11" },
    features: ["Ultra-thin design", "Wireless ring charger", "Somatic recovery metrics", "Dedicated health dashboard App"],
    color: "from-zinc-400 to-slate-600",
    iconName: "Watch",
    image: "https://images.unsplash.com/photo-1617042375876-a13e36732a04?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "wear-4",
    name: "Apex VR Headset Go",
    category: "Electronics",
    subCategory: "Wearables",
    price: 19990,
    originalPrice: 24999,
    rating: 4.8,
    reviews: 67,
    stock: 5,
    description: "Standalone virtual reality headset featuring 6DOF motion tracking, sharp dual LCD lenses, and built-in spatial speakers.",
    specs: { "Resolution": "1832x1920 per eye", "Refresh Rate": "90Hz", "Storage": "128GB", "Processor": "Snapdragon XR2" },
    features: ["No PC setup needed", "Precision touch hand controllers", "Guardian boundary safety grid", "Casting to TV enabled"],
    color: "from-indigo-600 to-purple-700",
    iconName: "Watch",
    image: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "wear-5",
    name: "HydraTracker Smart Bottle",
    category: "Electronics",
    subCategory: "Wearables",
    price: 3499,
    originalPrice: 4999,
    rating: 4.3,
    reviews: 82,
    stock: 22,
    description: "Stainless steel smart bottle that synchronizes your hydration logs, tracks daily targets, and sanitizes water with UV.",
    specs: { "Capacity": "650ml", "Material": "Double-wall 18/8 Steel", "Sanitizer": "Built-in UV-C Led", "Battery": "Rechargeable 10-day" },
    features: ["LED glow reminder logs", "Keeps cold 24h / hot 12h", "Sanitizes cap mechanism", "Bluetooth logs sync"],
    color: "from-blue-400 to-cyan-500",
    iconName: "Bottle",
    image: waterBottleImg
  },
  {
    id: "wear-6",
    name: "PulseFit GPS Smartwatch",
    category: "Electronics",
    subCategory: "Wearables",
    price: 8999,
    originalPrice: 12999,
    rating: 4.5,
    reviews: 94,
    stock: 14,
    description: "A mid-range fitness watch featuring offline map routes, built-in compass, and heart rate recovery calculations.",
    specs: { "Display": "1.3\" Transflective", "GPS": "Dual-Band Multi-GNSS", "Battery Life": "5 Days (GPS on)", "Waterproof": "5 ATM" },
    features: ["High-visibility sunlight display", "Running coach algorithms", "Barometric altimeter", "Sweat-wicking silicone band"],
    color: "from-blue-500 to-teal-500",
    iconName: "Watch",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "wear-7",
    name: "Chronos Swim tracker Watch",
    category: "Electronics",
    subCategory: "Wearables",
    price: 13499,
    originalPrice: 17999,
    rating: 4.6,
    reviews: 38,
    stock: 7,
    description: "Specialized swimming wearable tracking lap counts, SWOLF metrics, stroke types, and real-time underwater pulse.",
    specs: { "Waterproof": "10 ATM (100 meters)", "Display": "AMOLED color touch", "Battery Life": "7 Days", "Strap": "Anti-microbial silicone" },
    features: ["Automatic turn detection", "SWOLF score optimization", "Drill log options", "Vibration pacing alerts"],
    color: "from-cyan-600 to-indigo-600",
    iconName: "Watch",
    image: "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "wear-8",
    name: "AuraFit Smart Band Pro",
    category: "Electronics",
    subCategory: "Wearables",
    price: 4499,
    originalPrice: 6999,
    rating: 4.5,
    reviews: 104,
    stock: 25,
    description: "Upgraded smart tracker with a wider AMOLED color screen, built-in SpO2 sensor, and customizable widget tiles.",
    specs: { "Display": "1.64\" AMOLED", "Battery Life": "12 Days", "Waterproof": "5 ATM Rated", "Sensors": "Heart, SpO2, accelerometer" },
    features: ["Always-On clock mode", "Virtual run partner", "Music control panels", "Quick-reply messages (Android)"],
    color: "from-orange-500 to-red-500",
    iconName: "Watch",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "wear-9",
    name: "Smart Sleep Tracker Headband",
    category: "Electronics",
    subCategory: "Wearables",
    price: 9999,
    originalPrice: 14999,
    rating: 4.2,
    reviews: 29,
    stock: 0,
    description: "Comfortable fabric headband using micro-EEG sensors to analyze brain wave sleep cycles and wake you gently with audio waves.",
    specs: { "Material": "Washable Lycra-blend", "Battery": "12 Hours", "Connectivity": "Bluetooth Low Energy", "Sensors": "EEG, Actigraphy" },
    features: ["White noise audio library", "Binaural beat generators", "Smart alarms matching REM cycles", "Deep sleep logs analysis"],
    color: "from-purple-600 to-pink-500",
    iconName: "Watch",
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "wear-10",
    name: "AeroBone Bone Conduction Watch",
    category: "Electronics",
    subCategory: "Wearables",
    price: 10999,
    originalPrice: 15999,
    rating: 4.6,
    reviews: 41,
    stock: 8,
    description: "Outdoor smartwatch synced with bone-conduction audio plates behind the wrist, allowing you to hear audio notifications.",
    specs: { "Display": "1.39\" AMOLED", "Strap": "Titanium clasp", "Battery": "6 Days", "Audio Plates": "Dual bone-conduction transducers" },
    features: ["Open-ear notifications", "Emergency alert speakers", "Built-in GPS and maps", "Altimeter and Barometer gauges"],
    color: "from-zinc-600 to-slate-700",
    iconName: "Watch",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400&auto=format&fit=crop&q=60"
  },

  // --- SUB-CATEGORY: KEYBOARDS & MICE (21-30) ---
  {
    id: "key-1",
    name: "TitanMech Mechanical Keyboard",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 6999,
    originalPrice: 9999,
    rating: 4.8,
    reviews: 145,
    stock: 12,
    description: "Premium tenkeyless hot-swappable gaming keyboard featuring linear red mechanical switches and double-shot PBT keycaps.",
    specs: { "Form Factor": "80% Tenkeyless", "Switches": "Hot-swappable Linear Red", "Lighting": "Per-Key RGB", "Interface": "USB-C / 2.4GHz / BT" },
    features: ["Double-shot PBT Keycaps", "Lubed stabilizers", "CNC Aluminium top frame", "Sound-dampening foam layers"],
    color: "from-purple-600 to-pink-600",
    iconName: "Keyboard",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-2",
    name: "Apex Swift Gaming Mouse",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 3499,
    originalPrice: 4999,
    rating: 4.7,
    reviews: 198,
    stock: 25,
    description: "Ultra-lightweight gaming mouse weighing only 58 grams, equipped with a 26K DPI optical sensor and PTFE feet.",
    specs: { "Weight": "58 grams", "Sensor": "26,000 DPI Optical", "Battery Life": "80 Hours wireless", "Switches": "Optical (100M clicks)" },
    features: ["Superflex paracord cable", "Virgin-grade PTFE glides", "Zero latency wireless", "Custom button programming mapping"],
    color: "from-indigo-600 to-pink-500",
    iconName: "Mouse",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-3",
    name: "ErgoComfort Split Keyboard",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 11999,
    originalPrice: 15999,
    rating: 4.6,
    reviews: 57,
    stock: 8,
    description: "Ergonomic split keyboard designed to reduce wrist strain, featuring a 3D wave keybed and memory foam wrist rests.",
    specs: { "Form": "Split contoured layout", "Wrist Rest": "Cushioned memory foam", "Connectivity": "Bluetooth / wireless USB", "Battery": "2x AAA (Included)" },
    features: ["Adjustable tilt legs", "Dual split spacebars", "Logitech-style tactile keys", "Shortcut function dials"],
    color: "from-blue-600 to-indigo-700",
    iconName: "Keyboard",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-4",
    name: "Vanguard Trackball Pro",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 4999,
    originalPrice: 7999,
    rating: 4.4,
    reviews: 81,
    stock: 14,
    description: "Precision wireless trackball mouse with adjustable hinge angle (0 to 20 degrees) for customized forearm comfort.",
    specs: { "Trackball": "34mm optical sensor trackball", "Battery": "Rechargeable (up to 4 months)", "DPI": "320 - 440 adjustable", "Controls": "Scroll wheel + 8 keys" },
    features: ["Precision mode shortcut key", "Multi-device flow control", "Easy-to-clean ball socket", "Ergonomic thumb grip contour"],
    color: "from-zinc-500 to-slate-800",
    iconName: "Mouse",
    image: "https://images.unsplash.com/photo-1603481588273-2f908a9a7a1b?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-5",
    name: "NeonGlide RGB Mousepad XXL",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 1999,
    originalPrice: 2999,
    rating: 4.5,
    reviews: 132,
    stock: 40,
    description: "Over-sized gaming desk mat featuring water-resistant micro-woven cloth texture and 14-zone RGB light edges.",
    specs: { "Dimensions": "36\" x 16\" x 4mm", "Surface": "Micro-textured fabric", "Base": "Anti-slip rubber", "Power": "USB Powered (Plug & Play)" },
    features: ["Stitched light guides", "Waterproof spill barrier coating", "Brightness memory settings", "Optimized mouse tracking accuracy"],
    color: "from-red-500 to-orange-500",
    iconName: "Mousepad",
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-6",
    name: "LiteType Slim Wireless Keyboard",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 2499,
    originalPrice: 3999,
    rating: 4.3,
    reviews: 154,
    stock: 22,
    description: "Ultra-thin chiclet keyboard matching Mac/Windows setups, with rechargeable battery and silent scissor keycaps.",
    specs: { "Thickness": "5.5mm", "Keys": "Scissor mechanism keys", "Connectivity": "Bluetooth 3 channels", "Battery": "350mAh Lithium (recharges in 2h)" },
    features: ["Brushed metal panel feel", "Silent quiet typing", "Multi-device quick switches", "Media shortcut controls"],
    color: "from-slate-400 to-slate-500",
    iconName: "Keyboard",
    image: "https://images.unsplash.com/photo-1626908013351-800ddd734b8a?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-7",
    name: "Apex Precision Click Mouse",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 1299,
    originalPrice: 1999,
    rating: 4.2,
    reviews: 242,
    stock: 50,
    description: "Wired precision mouse with customizable DPI switches and ergonomic side grips. Ideal for daily office duties.",
    specs: { "Connection": "Wired USB (1.8m braided)", "Sensor": "DPI 800-4800 adjustable", "Weight": "90g", "Button Clicks": "20 Million rated" },
    features: ["Soft-touch plastic coating", "Tactile scroll wheel", "Thumb forward/back buttons", "RGB light highlights"],
    color: "from-blue-500 to-purple-500",
    iconName: "Mouse",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-8",
    name: "Keycap Customizer Set GMK",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 5999,
    originalPrice: 7999,
    rating: 4.9,
    reviews: 16,
    stock: 5,
    description: "Premium thick double-shot ABS keycaps set with customized retro dye-sublimation colorway. Cherry profile.",
    specs: { "Key Count": "135 Keys (Fits most layouts)", "Material": "ABS Double-shot", "Profile": "Cherry Profile", "Wall Thickness": "1.5mm" },
    features: ["Tolerant fitting cross stem", "No fading legends", "Includes custom novelties", "Includes wire keycap puller"],
    color: "from-amber-500 to-yellow-600",
    iconName: "Keyboard",
    image: "https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-9",
    name: "MechNumeric Numpad Wireless",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 2999,
    originalPrice: 4499,
    rating: 4.5,
    reviews: 34,
    stock: 12,
    description: "Add-on mechanical numeric keypad, ideal for bookkeeping and finance experts working on compact keyboards.",
    specs: { "Keys": "21 mechanical tactile keys", "Connectivity": "Bluetooth / 2.4GHz wireless", "Switches": "Tactile Brown", "Battery": "Type-C recharge (100h capacity)" },
    features: ["Dedicated backspace and tab keys", "Calculator launch shortcut", "Ergonomic step contour", "Under-glow white backlights"],
    color: "from-zinc-500 to-slate-700",
    iconName: "Keyboard",
    image: "https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "key-10",
    name: "Nomad Tech Gear Organizer Bag",
    category: "Electronics",
    subCategory: "Keyboards & Mice",
    price: 4499,
    originalPrice: 5999,
    rating: 4.6,
    reviews: 28,
    stock: 15,
    description: "Heavy-duty tech commuter organizer bag with padded laptop compartment, waterproof lining, and YKK zippers.",
    specs: { "Laptop Compartment": "Up to 16\" Laptop", "Material": "1680D Ballistic Nylon", "Waterproof": "Yes", "Capacity": "18 Liters" },
    features: ["TSA-friendly opening", "Hidden passport security pocket", "Luggage pass-through strap", "Dual side bottle pockets"],
    color: "from-slate-700 to-zinc-900",
    iconName: "Keyboard",
    image: backpackImg
  },

  // --- SUB-CATEGORY: SMART HOME (31-40) ---
  {
    id: "home-1",
    name: "OmniGuard Security Camera",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 4999,
    originalPrice: 7999,
    rating: 4.6,
    reviews: 198,
    stock: 22,
    description: "Wireless outdoor security camera featuring color night vision, motion sensors, and 2K resolution logs.",
    specs: { "Resolution": "2K Super HD", "Field of view": "130 degrees", "Battery Life": "6 Months charge", "Weatherproof": "IP65 Certified" },
    features: ["AI Person/Animal detection", "Built-in spotlight alarm", "Two-way talk speaker", "MicroSD and Cloud storage options"],
    color: "from-blue-500 to-indigo-600",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-2",
    name: "HaloLight Smart LED Bulb Pack",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 1999,
    originalPrice: 3499,
    rating: 4.5,
    reviews: 320,
    stock: 50,
    description: "Pack of 3 smart RGB LED light bulbs, compatible with Alexa and Google Assistant. No hub required.",
    specs: { "Brightness": "800 Lumens (60W Eq)", "Colors": "16 Million RGB colors", "Fitting": "E27 / B22 standard base", "Power": "9W usage" },
    features: ["App control timers", "Music rhythm sync mode", "Warm to cool whites tuning", "Group scenes control tabs"],
    color: "from-yellow-400 to-orange-500",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-3",
    name: "OmniPlug Smart Plug Pro",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 899,
    originalPrice: 1499,
    rating: 4.4,
    reviews: 412,
    stock: 80,
    description: "Wi-Fi smart socket enabling energy tracking, automatic countdown routines, and voice integrations.",
    specs: { "Max Load": "16A (High power appliances)", "Connectivity": "Wi-Fi 2.4GHz", "Safety": "Overload protection shutter", "Material": "Flame retardant PC" },
    features: ["Real-time power monitoring logs", "Away-mode scheduling simulator", "Compact space-saving layout", "Alexa/Google home voice controls"],
    color: "from-emerald-500 to-green-600",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-4",
    name: "SafeLock Keyless Deadbolt Pro",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 12999,
    originalPrice: 17999,
    rating: 4.8,
    reviews: 42,
    stock: 6,
    description: "High-security smart deadbolt, unlocking via biometric fingerprint, numerical keypad, NFC card, or phone.",
    specs: { "Lock Type": "Deadbolt lock replacement", "Unlock Modes": "5 modes (fingerprint, code, card, key, app)", "Battery Life": "12 Months (4x AA)", "Emergency Power": "Type-C USB terminal port" },
    features: ["Store 100 fingerprints", "Auto-lock timed safety", "Anti-peep password mask", "One-time guest pass codes generator"],
    color: "from-zinc-800 to-slate-900",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-5",
    name: "AeroBreeze Smart Air Purifier",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 9999,
    originalPrice: 14999,
    rating: 4.7,
    reviews: 65,
    stock: 10,
    description: "True HEPA air filter capturing 99.97% of allergens, smoke, and fine dust. Real-time air quality monitoring.",
    specs: { "CADR": "250 cubic meters/hour", "Filter": "3-Stage True HEPA H13", "Coverage area": "Up to 300 sq.ft", "Noise": "24dB ultra quiet sleep" },
    features: ["PM2.5 laser indicator panel", "Smart auto fan speed adjust", "Filter replacement dashboard alert", "Aromatherapy pad insert"],
    color: "from-cyan-400 to-blue-500",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-6",
    name: "SafeBell Video Doorbell Pro",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 6999,
    originalPrice: 9999,
    rating: 4.5,
    reviews: 84,
    stock: 15,
    description: "Wi-Fi smart video doorbell featuring head-to-toe HD framing, quick response audios, and package alarms.",
    specs: { "Resolution": "1080p HDR Video", "Aspect Ratio": "1:1 square view", "Power": "Wired or rechargeable battery", "Wi-Fi": "Dual-Band 2.4/5GHz" },
    features: ["Head-to-toe packaging scan", "Built-in siren alert", "Pre-recorded quick voice replies", "Chime receiver unit included"],
    color: "from-indigo-500 to-purple-600",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1562408590-e32931084e23?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-7",
    name: "ThermoSmart Climate Controller",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 8499,
    originalPrice: 11999,
    rating: 4.6,
    reviews: 33,
    stock: 9,
    description: "Learns your cooling/heating habits to optimize AC runtime, reducing your energy bill by up to 15%.",
    specs: { "AC compatibility": "99% split/window units with remote", "Sensor scope": "Temp, Humidity, Ambient Light", "Power": "USB Powered 5V/1A", "App": "iOS/Android dashboard" },
    features: ["Smart geolocation auto-on/off", "Energy savings monthly logs", "Voice assistant ready", "Multi-room temp balance linking"],
    color: "from-orange-600 to-red-500",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-8",
    name: "OmniHub Zigbee Smart Gateway",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 2499,
    originalPrice: 3999,
    rating: 4.4,
    reviews: 58,
    stock: 20,
    description: "Link up to 128 Zigbee sensors, smart buttons, and sirens to a secure unified smart home core.",
    specs: { "Protocol": "Zigbee 3.0 & BLE Mesh", "Ethernet": "RJ45 Port + Wi-Fi client", "Coverage Range": "100 meters open field", "Max Devices": "128 devices" },
    features: ["Local offline automation engines", "Low-power battery sensor links", "Pairing button controls", "Universal homekit compatibility"],
    color: "from-slate-500 to-slate-700",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-9",
    name: "SafeGuard Water Leak Sensor",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 1199,
    originalPrice: 1999,
    rating: 4.3,
    reviews: 47,
    stock: 35,
    description: "Place near washing machines or basins. Sends instant phone alerts and sounds siren upon detecting drops.",
    specs: { "Sensor": "Gold-plated probe legs", "Battery Life": "2 Years (CR2032)", "Waterproof": "IP67 sealed body", "Siren Decibel": "85dB at 3 meters" },
    features: ["Instant push alerts notification", "Battery check dashboard", "Compact floor flat placement", "Trigger link to main valves"],
    color: "from-cyan-500 to-blue-500",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "home-10",
    name: "AeroVent Smart Fan Controller",
    category: "Electronics",
    subCategory: "Smart Home",
    price: 3999,
    originalPrice: 5999,
    rating: 4.5,
    reviews: 24,
    stock: 12,
    description: "Replace standard wall dimmers. Instantly converts standard ceiling fans to smart speeds via Wi-Fi/app control.",
    specs: { "Load": "Max 1.5A inductive", "Speeds": "4 speed steps control", "Wall plate": "Standard modular switch width", "Led indicator": "White speed indicators" },
    features: ["Scheduler timer setup", "Natural breeze mode (cycles speeds)", "Voice dimming options", "Local manual touch toggles"],
    color: "from-blue-600 to-indigo-600",
    iconName: "Home",
    image: "https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?w=400&auto=format&fit=crop&q=60"
  },

  // --- SUB-CATEGORY: POWER & CABLES (41-50) ---
  {
    id: "pow-1",
    name: "VoltCharge 20000mAh Power Bank",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 2499,
    originalPrice: 3999,
    rating: 4.6,
    reviews: 310,
    stock: 40,
    description: "Heavy-duty power bank with 22.5W fast charge output, smart LCD power gauge, and multi-device ports.",
    specs: { "Capacity": "20,000mAh", "Ports": "2x USB-A output, 1x Type-C Bi-directional", "Max Output": "22.5W Power Delivery", "Weight": "340g" },
    features: ["Smart LCD percentage count display", "Low-current charging mode for bands", "Scratch-resistant carbon texture", "Includes short USB-C charging cord"],
    color: "from-indigo-500 to-blue-600",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-2",
    name: "VoltLink Braided USB-C Cable",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 499,
    originalPrice: 799,
    rating: 4.8,
    reviews: 512,
    stock: 100,
    description: "6.6ft heavy-duty double-braided nylon USB-C to USB-C cable supporting 100W PD charging speeds.",
    specs: { "Length": "6.6 feet (2 meters)", "Power Rating": "100W Power Delivery max", "Data Speed": "480 Mbps USB 2.0", "Material": "Double-braided ballistic nylon" },
    features: ["Anodized aluminium connector tips", "10,000 bend cycle testing guarantee", "Includes leather cable tie wrapper", "E-marker smart IC protection chip"],
    color: "from-zinc-500 to-slate-800",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-3",
    name: "VoltWall 65W GaN Charger",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 2999,
    originalPrice: 4499,
    rating: 4.7,
    reviews: 145,
    stock: 28,
    description: "Miniature Gallium Nitride multi-port wall adapter. Fast charges laptops, phones, and tablets at once.",
    specs: { "Technology": "GaN Fast charge", "Output Ports": "2x USB-C PD, 1x USB-A QC", "Total Power": "65W max sharing", "Plug Type": "Foldable pins" },
    features: ["35% smaller than traditional chargers", "Dynamic power allocation algorithm", "Over-heat thermal monitoring protections", "Travel voltage compatible (100-240V)"],
    color: "from-purple-600 to-indigo-700",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-4",
    name: "VoltStand 3-in-1 Charging Dock",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 3999,
    originalPrice: 5999,
    rating: 4.5,
    reviews: 78,
    stock: 15,
    description: "Sleek obsidian-glass charging stand powering your phone, watch, and wireless earbuds concurrently.",
    specs: { "Phone Charger": "15W MagSafe aligned Qi2", "Watch Charger": "5W magnetic apple watch platform", "Buds Charger": "5W Qi tray area", "Input": "Requires 9V/3A PD plug" },
    features: ["Ambient nightstand LED bar", "Case friendly charging (up to 4mm)", "Non-slip weighted iron foundation", "Tilt view optimal for video calling"],
    color: "from-blue-600 to-cyan-600",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-5",
    name: "VoltGuard 8-Socket Surge Protector",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 1799,
    originalPrice: 2999,
    rating: 4.6,
    reviews: 120,
    stock: 30,
    description: "Heavy-duty power strip guarding desktop rigs against power spike damages with integrated circuit breakers.",
    specs: { "Sockets": "8 Universal safety sockets", "Surge Protection": "2500 Joules rating", "Cord Length": "3 meters heavy duty", "USB Ports": "2x USB-A (5V/2.4A sharing)" },
    features: ["Grounded socket safety indicators", "Child safety shutter shields", "Master reset power breaker switch", "Wall mounts slots backing"],
    color: "from-slate-700 to-zinc-900",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-6",
    name: "VoltTravel Multi-Country Plug",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 1999,
    originalPrice: 2999,
    rating: 4.4,
    reviews: 94,
    stock: 22,
    description: "All-in-one international adapter covering UK, EU, US, and AU wall formats. Includes 4 USB ports.",
    specs: { "Sockets Cover": "150+ countries worldwide", "USB ports": "3x USB-A, 1x USB-C PD (30W)", "Safety fuse": "Dual auto-resetting 8A fuses", "Max Power": "880W at 110V / 1840W at 230V" },
    features: ["Slider format selectors", "Compact box travel profile", "Independent child shutters", "Glow led power tracker indicator"],
    color: "from-slate-400 to-slate-500",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1627856013091-fed6e4e30025?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-7",
    name: "VoltCharge 10000mAh Pocket Power",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 1299,
    originalPrice: 1999,
    rating: 4.5,
    reviews: 184,
    stock: 35,
    description: "Pocket-sized ultra-thin backup charger. Easily slips into jeans pockets for emergency top-ups.",
    specs: { "Capacity": "10,000mAh", "Thickness": "12mm", "Ports": "1x USB-A out, 1x USB-C PD (18W)", "Weight": "165g" },
    features: ["Pocket size format", "Fast recharging via Type-C", "Intelligent thermal checks", "Aircraft travel approved"],
    color: "from-rose-500 to-pink-500",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-8",
    name: "VoltLink Lightning Braided Cable",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 799,
    originalPrice: 1199,
    rating: 4.7,
    reviews: 210,
    stock: 60,
    description: "4.0ft durable MFi certified braided charging cord for iPhones and Apple accessories.",
    specs: { "Length": "4.0 feet (1.2 meters)", "Certification": "Apple MFi Certified", "Core": "Tinned copper fast cores", "Material": "Braided nylon cord" },
    features: ["Reinforced SR stress joints", "No error popup guarantee", "High speed power transmission", "Velcro cord manager wrap included"],
    color: "from-slate-500 to-zinc-600",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-9",
    name: "VoltDesk Magnetic Cable Organizer",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 599,
    originalPrice: 999,
    rating: 4.6,
    reviews: 87,
    stock: 45,
    description: "Keep charging cables from slipping off your desk. Heavy silicone base with 5 magnetic cord clips.",
    specs: { "Clips": "5 Magnetic locking collar loops", "Base Mount": "Washable sticky gel pad", "Material": "Anodized steel base + silicone", "Cable support": "Up to 5mm diameter cords" },
    features: ["Reusable sticky gel pad base", "Includes clips for flat cables", "Tear-resistant flexible rubber", "Obsidian black minimal design matches setups"],
    color: "from-zinc-600 to-slate-800",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&auto=format&fit=crop&q=60"
  },
  {
    id: "pow-10",
    name: "VoltDesk Wireless Charging Mat",
    category: "Electronics",
    subCategory: "Power & Cables",
    price: 4999,
    originalPrice: 7999,
    rating: 4.7,
    reviews: 19,
    stock: 8,
    description: "Elegant desk mat made of premium felt wool, featuring an integrated 15W wireless charging zone on the left.",
    specs: { "Dimensions": "31.5\" x 11.8\" felt mat", "Charging Zone": "15W Qi wireless plate built-in", "Power connection": "Type-C input (requires 18W adapter)", "Material": "Recycled Merino felt wool + cork backing" },
    features: ["Built-in temperature sensors", "Anti-fray edge stitch patterns", "Eco-friendly natural wool", "Keeps cables and chargers concealed"],
    color: "from-slate-600 to-zinc-700",
    iconName: "Bottle",
    image: "https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=400&auto=format&fit=crop&q=60"
  }
];

export const MOCK_ORDERS = [
  {
    id: "ORD-1001",
    date: "2026-06-01",
    total: 9999,
    status: "Delivered",
    items: [
      {
        productId: "aud-2",
        name: "AuraBeats Studio Headphones",
        price: 9999,
        quantity: 1
      }
    ],
    shipping: {
      name: "Alex Mercer",
      address: "742 Evergreen Terrace",
      city: "Springfield",
      zip: "97477",
      carrier: "FedEx",
      tracking: "TRK-9823049"
    },
    timeline: [
      { date: "2026-06-01 10:30 AM", status: "Order Placed", desc: "Payment processed successfully." },
      { date: "2026-06-01 03:45 PM", status: "Processed", desc: "Packed and prepared at distribution hub." },
      { date: "2026-06-02 08:00 AM", status: "Shipped", desc: "Handed over to carrier FedEx." },
      { date: "2026-06-04 02:15 PM", status: "Delivered", desc: "Left at front porch. Signed by resident." }
    ]
  },
  {
    id: "ORD-1002",
    date: "2026-06-10",
    total: 6999,
    status: "In Transit",
    items: [
      {
        productId: "key-1",
        name: "TitanMech Mechanical Keyboard",
        price: 6999,
        quantity: 1
      }
    ],
    shipping: {
      name: "Alex Mercer",
      address: "742 Evergreen Terrace",
      city: "Springfield",
      zip: "97477",
      carrier: "UPS",
      tracking: "TRK-7482910"
    },
    timeline: [
      { date: "2026-06-10 09:00 AM", status: "Order Placed", desc: "Payment received." },
      { date: "2026-06-10 02:30 PM", status: "Processed", desc: "Item packaged." },
      { date: "2026-06-11 11:00 AM", status: "Shipped", desc: "In transit from departure facility." },
      { date: "2026-06-13 06:15 AM", status: "In Transit", desc: "Arrived at local postal facility. Out for delivery soon." }
    ]
  },
  {
    id: "ORD-1003",
    date: "2026-06-12",
    total: 899,
    status: "Processing",
    items: [
      {
        productId: "home-3",
        name: "OmniPlug Smart Plug Pro",
        price: 899,
        quantity: 1
      }
    ],
    shipping: {
      name: "Alex Mercer",
      address: "742 Evergreen Terrace",
      city: "Springfield",
      zip: "97477",
      carrier: "DHL",
      tracking: "TRK-1293847"
    },
    timeline: [
      { date: "2026-06-12 05:40 PM", status: "Order Placed", desc: "Order details received." },
      { date: "2026-06-13 08:30 AM", status: "Processing", desc: "Verifying stocks and queueing packaging." }
    ]
  }
];

export const MOCK_COUPONS = {
  "SAVE10": 0.10,
  "WELCOME20": 0.20,
  "FREESHIP": 0.05,
  "CYBER30": 0.30
};
